version: '3.7'
services:
  app:
    container_name: ts-boilerplate-server
    restart: always
    build: .
    ports:
      - '80:4000'
    links:
      - mongo
    env_file:
      - ./.env
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
