curl 'https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=' \
-H 'Content-Type: application/json' \
--data-binary '{"email":"test@gmail.com","password":"test@123","returnSecureToken":true}'