curl 'https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=<API_KEY>' \
-H 'Content-Type: application/json' \
--data-binary '{"email":"test1@gmail.com","password":"test@123","returnSecureToken":true}'